//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsDurandal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aspect
    {
        public Aspect()
        {
            this.AspectInterpretations = new HashSet<AspectInterpretation>();
        }
    
        public byte AspectId { get; set; }
        public string AspectName { get; set; }
        public string HtmlTextCssClass { get; set; }
    
        public virtual ICollection<AspectInterpretation> AspectInterpretations { get; set; }
    }
}
