//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsDurandal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspectInterpretationType
    {
        public AspectInterpretationType()
        {
            this.AspectInterpretations = new HashSet<AspectInterpretation>();
            this.AspectInterpretations1 = new HashSet<AspectInterpretation>();
        }
    
        public byte AspectInterpretationTypeId { get; set; }
        public string AspectInterpretationTypeName { get; set; }
    
        public virtual ICollection<AspectInterpretation> AspectInterpretations { get; set; }
        public virtual ICollection<AspectInterpretation> AspectInterpretations1 { get; set; }
    }
}
