//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsDurandal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CelestialObject
    {
        public CelestialObject()
        {
            this.ChartObjects = new HashSet<ChartObject>();
            this.AspectInterpretations = new HashSet<AspectInterpretation>();
            this.AspectInterpretations1 = new HashSet<AspectInterpretation>();
        }
    
        public int CelestialObjectId { get; set; }
        public string CelestialObjectName { get; set; }
        public string AlternateName { get; set; }
        public byte CelestialObjectTypeId { get; set; }
        public decimal AllowableOrb { get; set; }
        public string Keywords { get; set; }
        public bool Draconic { get; set; }
    
        public virtual CelestialObjectType CelestialObjectType { get; set; }
        public virtual ICollection<ChartObject> ChartObjects { get; set; }
        public virtual ICollection<AspectInterpretation> AspectInterpretations { get; set; }
        public virtual ICollection<AspectInterpretation> AspectInterpretations1 { get; set; }
    }
}
