//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsDurandal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CelestialObjectType
    {
        public CelestialObjectType()
        {
            this.CelestialObjects = new HashSet<CelestialObject>();
        }
    
        public byte CelestialObjectTypeId { get; set; }
        public string CelestialObjectTypeName { get; set; }
    
        public virtual ICollection<CelestialObject> CelestialObjects { get; set; }
    }
}
