//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsDurandal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartHouse
    {
        public int ChartHouseId { get; set; }
        public int EnteredChartId { get; set; }
        public byte HouseSystemId { get; set; }
        public byte HouseId { get; set; }
        public byte SignId { get; set; }
        public byte Degrees { get; set; }
        public byte Minutes { get; set; }
        public byte Seconds { get; set; }
    
        public virtual EnteredChart EnteredChart { get; set; }
        public virtual HouseCusp HouseCusp { get; set; }
        public virtual HouseSystem HouseSystem { get; set; }
        public virtual Sign Sign { get; set; }
    }
}
