//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsDurandal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseAngle
    {
        public HouseAngle()
        {
            this.ChartAngles = new HashSet<ChartAngle>();
            this.RelocatedChartAngles = new HashSet<RelocatedChartAngle>();
            this.AspectInterpretations = new HashSet<AspectInterpretation>();
            this.AspectInterpretations1 = new HashSet<AspectInterpretation>();
        }
    
        public byte AngleId { get; set; }
        public string AngleName { get; set; }
    
        public virtual ICollection<ChartAngle> ChartAngles { get; set; }
        public virtual ICollection<RelocatedChartAngle> RelocatedChartAngles { get; set; }
        public virtual ICollection<AspectInterpretation> AspectInterpretations { get; set; }
        public virtual ICollection<AspectInterpretation> AspectInterpretations1 { get; set; }
    }
}
