//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsDurandal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quality
    {
        public Quality()
        {
            this.Signs = new HashSet<Sign>();
        }
    
        public byte QualityId { get; set; }
        public string QualityName { get; set; }
    
        public virtual ICollection<Sign> Signs { get; set; }
    }
}
