//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsDurandal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelocatedChart
    {
        public RelocatedChart()
        {
            this.RelocatedChartAngles = new HashSet<RelocatedChartAngle>();
            this.RelocatedChartHouses = new HashSet<RelocatedChartHous>();
        }
    
        public int RelocatedChartId { get; set; }
        public string RelocatedLocation { get; set; }
        public System.DateTime RelocatedDateTime { get; set; }
        public int EnteredChartId { get; set; }
    
        public virtual EnteredChart EnteredChart { get; set; }
        public virtual ICollection<RelocatedChartAngle> RelocatedChartAngles { get; set; }
        public virtual ICollection<RelocatedChartHous> RelocatedChartHouses { get; set; }
    }
}
